config/routes.rb
FbAuthenticatable::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get "/logout" => "devise/sessions#destroy"
  end

  resources :users, :only => [] do
    collection do
      get :sign_in
      get :welcome
    end
  end

  root :to => 'users#welcome'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :omniauthable
  
  def self.find_or_create_by_facebook(data)
    self.find_or_create_by_facebook_id(data['extra']['raw_info']['id'], :facebook_token => data['credentials']['token'])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_or_create_by_facebook(request.env["omniauth.auth"])
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in :user, @user, :event => :authentication
      render 'shared/close_popup'
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      flash[:error] = "There was a problem with logging in. Please try again."
      render :text => "There was a problem with logging in. Please try again."
    end
  end

  def failure
    flash[:error] = "There was a problem with logging in. Please try again."
    render :text => "There was a problem with logging in. Please try again."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def sign_in
    redirect_to :action => 'welcome' if user_signed_in?
  end

  def welcome
    redirect_to :action => 'sign_in' unless user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      FbAuthenticatable
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      .content
        = yield

app/views/shared/close_popup.html.haml
:javascript
  if(window.opener) {
    window.opener.location.reload(true);
    window.close()
  }

app/views/users/sign_in.html.haml
.row
  .span16
    .page-header
      %h1
        Sign In
.row
  .span16
    %p
      = link_to "Log in with Facebook", omniauth_authorize_path(:user, :facebook), :class => "popup btn-auth btn-facebook", :"data-width" => 600, :"data-height" => 400

app/views/users/welcome.html.haml
.row
  .span16
    .page-header
      %h1
        Welcome
    %p
      You have signed in successfully
    %p
      = link_to 'Log Out', logout_path